// AUTO-GENERATED by scripts/gen-legal.mjs from the lawyer's finalised ODT
// documents. Full text, verbatim — do not edit by hand; re-run the generator.
export interface LegalBlock {
  t: 'h' | 'p' | 'li';
  s: string;
}
export interface LegalDocContent {
  title: string;
  updated: string;
  blocks: LegalBlock[];
}

export const PRIVACY: LegalDocContent = {
  title: "Politica de Confidențialitate",
  updated: "2 iulie 2026",
  blocks: [
    {
      "t": "h",
      "s": "1. Operatorul de date"
    },
    {
      "t": "p",
      "s": "SOCIETATEA Deco kubik srl S.R.L., cu sediul în Bucuresti str Odobesti 13, blv35/60, înregistrată la Oficiul Registrului Comerțului sub nr. J40/64417/2008, având CUI RO24386414 (denumită în continuare „Operatorul”), prelucrează datele cu caracter personal prin intermediul Platformei Craft'zaar, în calitate de operator de date, în conformitate cu Regulamentul (UE) 2016/679 privind protecția persoanelor fizice în ceea ce privește prelucrarea datelor cu caracter personal („GDPR”) și cu legislația națională aplicabilă."
    },
    {
      "t": "p",
      "s": "Prezenta Politică de Confidențialitate descrie modul în care Operatorul colectează, utilizează, stochează, divulgă și protejează datele cu caracter personal prelucrate prin intermediul Platformei Craft'zaar."
    },
    {
      "t": "p",
      "s": "Pentru orice întrebări privind prelucrarea datelor cu caracter personal sau pentru exercitarea drepturilor prevăzute de GDPR, ne puteți contacta la adresa de e-mail: info.craftology.shop@gmail.com"
    },
    {
      "t": "p",
      "s": "Platforma Craft'zaar facilitează interacțiunea dintre Cumpărători și Vânzători independenți. În ceea ce privește produsele comercializate prin intermediul Platformei, fiecare Vânzător prelucrează, în calitate de operator de date distinct, datele cu caracter personal necesare executării comenzilor, procesării plăților în relația cu furnizorul de servicii de plată, emiterii documentelor fiscale, livrării produselor, soluționării retururilor, reclamațiilor, garanțiilor și îndeplinirii obligațiilor legale care îi revin."
    },
    {
      "t": "p",
      "s": "Prezenta Politică de Confidențialitate reglementează exclusiv prelucrarea datelor cu caracter personal efectuată de Operator prin intermediul Platformei Craft'zaar. Pentru prelucrările realizate de Vânzători în calitate de operatori de date independenți, aceștia răspund în mod direct pentru respectarea obligațiilor prevăzute de legislația aplicabilă în materia protecției datelor cu caracter personal."
    },
    {
      "t": "h",
      "s": "2. Ce date cu caracter personal prelucrăm"
    },
    {
      "t": "p",
      "s": "În funcție de calitatea utilizatorului (Cumpărător sau Vânzător) și de modul în care acesta utilizează Platforma Craftology, Operatorul poate prelucra următoarele categorii de date cu caracter personal:"
    },
    {
      "t": "p",
      "s": "Date aferente contului de utilizator:"
    },
    {
      "t": "p",
      "s": "Pentru utilizatorii care își creează un cont pe Platformă (Cumpărători și Vânzători), Operatorul poate prelucra următoarele date:"
    },
    {
      "t": "li",
      "s": "nume și prenume, după caz;"
    },
    {
      "t": "li",
      "s": "adresă de e-mail;"
    },
    {
      "t": "li",
      "s": "nume de utilizator (username);"
    },
    {
      "t": "li",
      "s": "parolă, stocată în format criptat prin intermediul serviciului Supabase;"
    },
    {
      "t": "p",
      "s": "fotografie de profil și alte informații de profil, în măsura în care utilizatorul alege să le completeze."
    },
    {
      "t": "p",
      "s": "În situația în care un Cumpărător achiziționează produse prin intermediul Platformei fără crearea unui cont de utilizator, Operatorul nu colectează și nu stochează datele de identificare ale acestuia, precum numele, adresa de livrare, adresa de e-mail sau datele aferente instrumentelor de plată. Aceste informații sunt prelucrate exclusiv prin intermediul platformei Stripe, în cadrul contului de comerciant al Vânzătorului, în conformitate cu politicile și condițiile aplicabile acestui furnizor de servicii de plată."
    },
    {
      "t": "p",
      "s": "În această situație, Platforma înregistrează exclusiv informațiile necesare administrării produselor comercializate, precum actualizarea statutului produsului (de exemplu, marcarea acestuia ca fiind vândut), fără a stoca date cu caracter personal referitoare la Cumpărător."
    },
    {
      "t": "p",
      "s": "În schimb, dacă un Cumpărător optează pentru crearea unui cont de utilizator, inclusiv în scopul utilizării funcționalității de transmitere a mesajelor către Vânzători, Operatorul va prelucra și stoca datele aferente contului de utilizator, în condițiile prezentei Politici."
    },
    {
      "t": "h",
      "s": "Date prelucrate în legătură cu comenzile și comunicarea dintre utilizatori"
    },
    {
      "t": "p",
      "s": "Operatorul poate prelucra:"
    },
    {
      "t": "li",
      "s": "informațiile necesare administrării comenzilor și funcționării Platformei, în măsura în care acestea sunt generate prin utilizarea unui cont de utilizator sau sunt necesare administrării produselor comercializate prin intermediul Platformei;"
    },
    {
      "t": "li",
      "s": "istoricul comenzilor aferent conturilor de utilizator, după caz;"
    },
    {
      "t": "p",
      "s": "mesajele și comunicările transmise între Cumpărători și Vânzători prin intermediul Platformei, în măsura în care această funcționalitate este disponibilă."
    },
    {
      "t": "p",
      "s": "Datele aferente instrumentelor de plată, precum și datele de identificare ale Cumpărătorilor necesare procesării plăților nu sunt colectate, accesate sau stocate de către Operator, acestea fiind prelucrate exclusiv prin intermediul platformei Stripe, în conformitate cu propriile politici și măsuri de securitate."
    },
    {
      "t": "h",
      "s": "Date prelucrate în legătură cu Vânzătorii"
    },
    {
      "t": "p",
      "s": "Operatorul poate prelucra următoarele categorii de date referitoare la Vânzători:"
    },
    {
      "t": "li",
      "s": "denumirea societății sau a entității care comercializează produse prin intermediul Platformei;"
    },
    {
      "t": "li",
      "s": "codul unic de înregistrare (CUI), după caz;"
    },
    {
      "t": "li",
      "s": "datele de contact (adresă de e-mail, număr de telefon sau alte date de contact puse la dispoziția Cumpărătorilor);"
    },
    {
      "t": "li",
      "s": "descrierea atelierului sau a activității desfășurate;"
    },
    {
      "t": "li",
      "s": "identificatorul contului Stripe Connect;"
    },
    {
      "t": "p",
      "s": "informații privind acceptarea Termenilor și Condițiilor Platformei (data și momentul exprimării acordului)."
    },
    {
      "t": "p",
      "s": "Verificarea identității Vânzătorilor, atunci când este necesară, este realizată de Stripe. Operatorul nu colectează și nu stochează documentele de identitate utilizate în cadrul acestui proces."
    },
    {
      "t": "h",
      "s": "Date privind produsele publicate pe Platformă"
    },
    {
      "t": "p",
      "s": "În vederea administrării Platformei și publicării ofertelor Vânzătorilor, Operatorul poate prelucra:"
    },
    {
      "t": "li",
      "s": "denumirea produsului;"
    },
    {
      "t": "li",
      "s": "descrierea produsului;"
    },
    {
      "t": "li",
      "s": "categoria din care face parte produsul;"
    },
    {
      "t": "li",
      "s": "prețul produsului;"
    },
    {
      "t": "p",
      "s": "fotografiile produselor încărcate de Vânzători."
    },
    {
      "t": "h",
      "s": "Date tehnice"
    },
    {
      "t": "p",
      "s": "Operatorul poate prelucra și anumite date tehnice generate de utilizarea Platformei, precum:"
    },
    {
      "t": "li",
      "s": "adresa IP;"
    },
    {
      "t": "li",
      "s": "informații privind dispozitivul și browserul utilizat;"
    },
    {
      "t": "p",
      "s": "date privind utilizarea Platformei și interacțiunea cu serviciile oferite (analytics), în măsura în care acestea sunt colectate."
    },
    {
      "t": "p",
      "s": "Categoriile de date cu caracter personal prelucrate pot varia în funcție de tipul contului utilizat (Cumpărător sau Vânzător), de serviciile accesate și de funcționalitățile Platformei utilizate de fiecare utilizator."
    },
    {
      "t": "h",
      "s": "3. Scopurile și temeiurile legale ale prelucrării datelor cu caracter personal"
    },
    {
      "t": "p",
      "s": "Operatorul prelucrează datele cu caracter personal exclusiv în scopuri determinate, explicite și legitime și numai în măsura în care există un temei legal pentru fiecare activitate de prelucrare, în conformitate cu art. 6 din Regulamentul (UE) 2016/679 (GDPR)."
    },
    {
      "t": "li",
      "s": "Crearea și administrarea contului: Pentru crearea și administrarea conturilor de Cumpărător și Vânzător, autentificarea utilizatorilor, gestionarea profilului acestora și asigurarea funcționalităților disponibile în cadrul Platformei Craft'zaar, Operatorul prelucrează datele cu caracter personal necesare furnizării acestor servicii, având ca temei juridic executarea serviciilor oferite prin intermediul Platformei."
    },
    {
      "t": "li",
      "s": "Intermedierea vânzărilor și facilitarea procesării plăților: În vederea administrării comenzilor plasate prin intermediul Platformei Craft'zaar, facilitării relației dintre Cumpărători și Vânzători și facilitării procesării plăților prin intermediul furnizorului de servicii de plată integrat în Platformă, Operatorul prelucrează datele cu caracter personal necesare furnizării serviciilor oferite prin intermediul Platformei, având ca temei juridic executarea contractului încheiat cu utilizatorii Platformei."
    },
    {
      "t": "li",
      "s": "Verificarea Vânzătorilor: Operatorul prelucrează datele cu caracter personal ale Vânzătorilor pentru verificarea identității acestora, confirmarea îndeplinirii condițiilor necesare utilizării Platformei Craft'zaar în această calitate, prevenirea utilizării frauduloase a Platformei, asigurarea unui mediu comercial sigur pentru utilizatori și respectarea obligațiilor legale aplicabile, având ca temei juridic îndeplinirea obligațiilor legale și interesul legitim al Operatorului de a asigura funcționarea în condiții de siguranță a Platformei și de a proteja interesele utilizatorilor acesteia."
    },
    {
      "t": "li",
      "s": "Comunicări privind comenzile și utilizarea Platformei: Operatorul utilizează datele cu caracter personal pentru transmiterea confirmărilor de comandă, notificărilor privind procesarea și livrarea comenzilor, comunicărilor administrative referitoare la contul de utilizator și funcționarea Platformei Craft'zaar, precum și pentru furnizarea informațiilor necesare utilizării serviciilor oferite prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "În măsura în care Platforma pune la dispoziția utilizatorilor o funcționalitate de comunicare între Cumpărători și Vânzători, datele aferente acestor comunicări pot fi prelucrate în scopul asigurării funcționării acestei facilități. Prelucrarea datelor are ca temei juridic executarea contractului privind utilizarea Platformei."
    },
    {
      "t": "li",
      "s": "Securitatea Platformei și prevenirea fraudelor: Datele cu caracter personal pot fi prelucrate pentru asigurarea securității Platformei Craft'zaar, prevenirea și identificarea tentativelor de fraudă, a accesului neautorizat sau a altor activități care pot afecta funcționarea acesteia, gestionarea incidentelor de securitate și protejarea drepturilor și intereselor legitime ale Operatorului, Vânzătorilor și Cumpărătorilor. Temeiul juridic al acestei prelucrări îl reprezintă interesul legitim al Operatorului de a asigura funcționarea Platformei în condiții de siguranță."
    },
    {
      "t": "p",
      "s": "Analiza și îmbunătățirea serviciilor: Datele cu caracter personal pot fi utilizate pentru analizarea modului de utilizare a Platformei Craft'zaar, evaluarea performanței și funcționalităților acesteia, identificarea și remedierea eventualelor disfuncționalități, precum și pentru dezvoltarea și îmbunătățirea serviciilor oferite. Această prelucrare se întemeiază pe interesul legitim al Operatorului de a optimiza funcționarea Platformei și experiența utilizatorilor."
    },
    {
      "t": "p",
      "s": "În măsura în care legislația aplicabilă impune obținerea consimțământului utilizatorului pentru anumite activități de analiză, monitorizare sau utilizarea unor tehnologii specifice, prelucrarea va avea loc numai în baza consimțământului exprimat de acesta."
    },
    {
      "t": "h",
      "s": "4. Destinatarii datelor cu caracter personal"
    },
    {
      "t": "p",
      "s": "Operatorul poate divulga datele cu caracter personal numai în măsura în care acest lucru este necesar pentru furnizarea serviciilor oferite prin intermediul Platformei Craftology, îndeplinirea obligațiilor legale care îi revin sau protejarea drepturilor și intereselor legitime ale Operatorului, ale Vânzătorilor și ale Cumpărătorilor."
    },
    {
      "t": "p",
      "s": "În funcție de activitățile desfășurate prin intermediul Platformei, datele cu caracter personal pot fi comunicate următoarelor categorii de destinatari:"
    },
    {
      "t": "li",
      "s": "Supabase – furnizorul serviciilor de găzduire și administrare a bazei de date a Platformei, autentificare a utilizatorilor și stocare a informațiilor aferente conturilor de utilizator, mesajelor, produselor, fotografiilor și datelor privind Vânzătorii;"
    },
    {
      "t": "li",
      "s": "Stripe – furnizorul serviciilor de procesare a plăților și, după caz, de verificare a identității Vânzătorilor. Operatorul nu colectează și nu stochează datele aferente instrumentelor de plată și nici datele de identificare ale Cumpărătorilor necesare procesării plăților, acestea fiind prelucrate exclusiv prin intermediul platformei Stripe, în conformitate cu politicile și condițiile aplicabile acestui furnizor de servicii de plată;"
    },
    {
      "t": "li",
      "s": "Vercel – furnizorul serviciilor de găzduire, administrare și mentenanță a Platformei, precum și, după caz, al serviciilor de analiză a performanței și utilizării acesteia (Vercel Analytics și Speed Insights);"
    },
    {
      "t": "li",
      "s": "Upstash – furnizorul serviciilor utilizate pentru limitarea solicitărilor adresate Platformei și prevenirea utilizării abuzive a acesteia;"
    },
    {
      "t": "li",
      "s": "ui-avatars.com – furnizor utilizat pentru generarea automată a imaginilor de profil (avatar) în situația în care utilizatorul nu încarcă o fotografie proprie. În acest scop poate fi transmis numele utilizatorului, exclusiv în măsura necesară generării avatarului;"
    },
    {
      "t": "li",
      "s": "furnizori de servicii de e-mail și comunicare, în măsura în care utilizarea acestora este necesară pentru funcționarea Platformei;"
    },
    {
      "t": "li",
      "s": "Vânzătorii, care primesc exclusiv datele cu caracter personal necesare executării comenzilor și îndeplinirii obligațiilor care le revin în calitate de comercianți și operatori de date independenți. Datele de contact ale Vânzătorilor sunt puse la dispoziția Cumpărătorilor în măsura necesară comunicării directe privind comenzile și produsele comercializate;"
    },
    {
      "t": "p",
      "s": "autoritățile și instituțiile publice competente, în situațiile în care divulgarea datelor este impusă de lege sau solicitată în mod legal."
    },
    {
      "t": "p",
      "s": "Operatorul poate utiliza și alți furnizori de servicii specializați, în măsura în care acest lucru este necesar pentru funcționarea, dezvoltarea, administrarea sau securizarea Platformei Craftology. În măsura în care acești furnizori prelucrează date cu caracter personal în numele și pe seama Operatorului, prelucrarea se va realiza exclusiv în baza instrucțiunilor Operatorului și cu respectarea cerințelor prevăzute de Regulamentul (UE) 2016/679 (GDPR)."
    },
    {
      "t": "p",
      "s": "Operatorul nu vinde, nu închiriază și nu divulgă datele cu caracter personal către terți în scopuri comerciale."
    },
    {
      "t": "p",
      "s": "Operatorul utilizează furnizori de servicii care pot prelucra date cu caracter personal atât în cadrul Spațiului Economic European, cât și, după caz, în afara acestuia."
    },
    {
      "t": "p",
      "s": "În situația în care utilizarea anumitor furnizori de servicii implică transferul datelor cu caracter personal către state din afara SEE, Operatorul se asigură că aceste transferuri sunt efectuate cu respectarea dispozițiilor Regulamentului (UE) 2016/679 (GDPR), exclusiv în baza unor garanții adecvate prevăzute de legislația aplicabilă, inclusiv prin utilizarea clauzelor contractuale standard aprobate de Comisia Europeană sau a altor mecanisme de transfer recunoscute de legislația aplicabilă. Astfel de transferuri pot avea loc în cazul utilizării unor servicii de găzduire cloud, analiză a performanței și utilizării Platformei, procesare a plăților sau al altor servicii furnizate de companii care prelucrează date cu caracter personal în afara SEE."
    },
    {
      "t": "h",
      "s": "5. Cât timp păstrăm datele cu caracter personal"
    },
    {
      "t": "p",
      "s": "Datele cu caracter personal sunt păstrate numai pe perioada necesară îndeplinirii scopurilor pentru care au fost colectate și prelucrate, cu respectarea prevederilor legale aplicabile."
    },
    {
      "t": "p",
      "s": "În general, datele cu caracter personal sunt păstrate pe durata existenței contului de utilizator și, ulterior, pentru perioada impusă de obligațiile legale aplicabile Operatorului, inclusiv în materie fiscală, contabilă sau de arhivare."
    },
    {
      "t": "p",
      "s": "La solicitarea persoanei vizate, Operatorul va analiza cererea de ștergere a datelor cu caracter personal și, în măsura în care sunt îndeplinite condițiile prevăzute de Regulamentul (UE) 2016/679 (GDPR), va șterge sau anonimiza datele care nu mai sunt necesare pentru îndeplinirea scopurilor pentru care au fost prelucrate ori pentru respectarea obligațiilor legale care îi revin. În situațiile în care legislația impune păstrarea anumitor date pentru o perioadă determinată, acestea vor fi păstrate până la expirarea termenelor legale aplicabile."
    },
    {
      "t": "h",
      "s": "6. Drepturile persoanelor vizate"
    },
    {
      "t": "p",
      "s": "În conformitate cu Regulamentul (UE) 2016/679 (GDPR), persoanele ale căror date cu caracter personal sunt prelucrate prin intermediul Platformei Craft'zaar beneficiază de următoarele drepturi:"
    },
    {
      "t": "li",
      "s": "dreptul de acces la datele cu caracter personal;"
    },
    {
      "t": "li",
      "s": "dreptul la rectificarea datelor inexacte sau incomplete;"
    },
    {
      "t": "li",
      "s": "dreptul la ștergerea datelor („dreptul de a fi uitat”), în cazurile prevăzute de lege;"
    },
    {
      "t": "li",
      "s": "dreptul la restricționarea prelucrării datelor;"
    },
    {
      "t": "li",
      "s": "dreptul la portabilitatea datelor;"
    },
    {
      "t": "li",
      "s": "dreptul de opoziție la prelucrarea datelor, în condițiile prevăzute de lege;"
    },
    {
      "t": "li",
      "s": "dreptul de a vă retrage consimțământul în orice moment, atunci când prelucrarea se întemeiază pe acesta, fără a afecta legalitatea prelucrării efectuate anterior retragerii;"
    },
    {
      "t": "p",
      "s": "dreptul de a depune o plângere la Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP)."
    },
    {
      "t": "p",
      "s": "Pentru exercitarea acestor drepturi sau pentru orice solicitare privind prelucrarea datelor cu caracter personal, ne puteți contacta la adresa de e-mail: info.craftology.shop@gmail.com"
    },
    {
      "t": "p",
      "s": "Informații suplimentare privind activitatea Autorității Naționale de Supraveghere a Prelucrării Datelor cu Caracter Personal sunt disponibile pe site-ul oficial: www.dataprotection.ro."
    },
    {
      "t": "p",
      "s": "7. Securitatea datelor cu caracter personal:"
    },
    {
      "t": "p",
      "s": "Operatorul implementează măsuri tehnice și organizatorice adecvate pentru protejarea datelor cu caracter personal împotriva accesului neautorizat, pierderii, distrugerii, modificării sau divulgării neautorizate."
    },
    {
      "t": "p",
      "s": "În acest scop, Operatorul utilizează măsuri de securitate adecvate, care pot include, după caz, criptarea datelor în tranzit, mecanisme de control al accesului, restricționarea accesului la bazele de date și alte măsuri tehnice și organizatorice destinate protejării datelor cu caracter personal."
    },
    {
      "t": "p",
      "s": "8. Cookie-uri: Platforma Craftology utilizează cookie-uri și tehnologii similare în condițiile prevăzute în Politica de Cookie-uri, document distinct, disponibil pe Platformă, care completează prezenta Politică de Confidențialitate."
    },
    {
      "t": "p",
      "s": "9. Modificări ale Politicii de Confidențialitate: Operatorul își rezervă dreptul de a modifica sau actualiza prezenta Politică de Confidențialitate ori de câte ori este necesar, inclusiv ca urmare a modificărilor legislative, a schimbărilor intervenite în funcționarea Platformei Craftology sau a modului de prelucrare a datelor cu caracter personal."
    },
    {
      "t": "p",
      "s": "Versiunea în vigoare este cea publicată pe Platformă, iar data ultimei actualizări este indicată la începutul prezentei Politici de Confidențialitate."
    },
    {
      "t": "p",
      "s": "Pentru orice întrebări privind prelucrarea datelor cu caracter personal sau pentru exercitarea drepturilor prevăzute de GDPR, ne puteți contacta la adresa de e-mail: info.craftology.shop@gmail.com"
    }
  ],
};

export const TERMS: LegalDocContent = {
  title: "Termeni și Condiții",
  updated: "2 iulie 2026",
  blocks: [
    {
      "t": "h",
      "s": "Cine suntem"
    },
    {
      "t": "p",
      "s": "Platforma Craft'zaar (denumită în continuare „Platforma”) este operată de SOCIETATEA Deco Kubik srl persoană juridică română, înregistrată la Registrul Comerțului sub nr.J40/64417/2008 cu sediul înBucuresti, str Odobesti 13/ aprt 60 email l.decokubik@gmail.com. Telefon 0732 781 226(denumită în continuare „Operatorul”, „noi” sau „Craft'zaar”)."
    },
    {
      "t": "p",
      "s": "Prin accesarea, navigarea, crearea unui cont ori utilizarea în orice mod a Platformei Craft'zaar, utilizatorul confirmă că a citit, a înțeles și a acceptat integral prezentele Termene și Condiții."
    },
    {
      "t": "p",
      "s": "Dacă nu ești de acord cu prezentele Termene și Condiții, te rugăm să nu utilizezi Platforma."
    },
    {
      "t": "p",
      "s": "Prezentele Termene și Condiții se completează cu Politica de Confidențialitate, Politica de Cookies, Politica de Retururi și Rambursări, precum și, în cazul vânzătorilor, cu Acordul Vânzătorului."
    },
    {
      "t": "h",
      "s": "Definiții"
    },
    {
      "t": "p",
      "s": "În cuprinsul prezentelor Termene și Condiții, termenii de mai jos vor avea următorul înțeles:"
    },
    {
      "t": "p",
      "s": "Platforma – aplicația și/sau site-ul web Craftology, precum și toate serviciile, funcționalitățile, paginile, conținutul și instrumentele puse la dispoziția utilizatorilor prin intermediul acesteia."
    },
    {
      "t": "p",
      "s": "Operatorul – societatea care administrează și operează Platforma Craft'zaar."
    },
    {
      "t": "p",
      "s": "Utilizator – orice persoană fizică având cel puțin 18 ani și capacitate deplină de exercițiu ori persoană juridică, care accesează, navighează, utilizează sau interacționează în orice mod cu Platforma."
    },
    {
      "t": "p",
      "s": "Cumpărător – orice persoană fizică sau juridică ce achiziționează ori intenționează să achiziționeze produse prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Consumator – orice persoană fizică ce acționează în scopuri care nu intră în cadrul activității sale comerciale, industriale, artizanale ori profesionale."
    },
    {
      "t": "p",
      "s": "Vânzător – orice persoană juridică, PFA, întreprindere individuală sau alt profesionist autorizat, aprobat de Operator pentru comercializarea prin intermediul Platformei a produselor handmade, în condițiile stabilite de prezentele Termene și Condiții și de Acordul Vânzătorului."
    },
    {
      "t": "p",
      "s": "Cont – secțiunea personală creată în Platformă, accesibilă pe baza datelor de autentificare."
    },
    {
      "t": "p",
      "s": "Produs handmade – orice bun realizat integral sau preponderent prin activitatea creativă, manuală ori artizanală a Vânzătorului, inclusiv produsele personalizate sau realizate la comandă. Nu sunt considerate produse handmade produsele industriale de serie, produsele achiziționate în vederea revânzării, produsele de import comercializate ca atare sau orice alte produse care nu corespund specificului artizanal al Platformei."
    },
    {
      "t": "p",
      "s": "Comandă – solicitarea transmisă de cumpărător în vederea achiziționării unuia sau mai multor produse listate pe Platformă."
    },
    {
      "t": "p",
      "s": "Contract de vânzare – contractul încheiat între cumpărător și Vânzător prin intermediul Platformei, având ca obiect achiziționarea produselor listate."
    },
    {
      "t": "p",
      "s": "Conținut – orice informație, text, imagine, fotografie, videoclip, element grafic, recenzie, comentariu, evaluare, descriere de produs, marcă, logo sau orice alt material disponibil pe Platformă."
    },
    {
      "t": "p",
      "s": "Conținut ilegal – orice informație, produs, material sau activitate care încalcă legislația aplicabilă, drepturile terților sau prezentele Termene și Condiții."
    },
    {
      "t": "p",
      "s": "Proprietate intelectuală – totalitatea drepturilor de autor, mărcilor, desenelor și modelelor, brevetelor, know-how-ului și oricăror alte drepturi similare recunoscute de legislația aplicabilă."
    },
    {
      "t": "p",
      "s": "Comunicări comerciale – orice comunicare transmisă prin e-mail, SMS, notificare în aplicație sau prin alte mijloace electronice, având caracter informativ, promoțional sau comercial."
    },
    {
      "t": "p",
      "s": "Servicii ale Platformei – totalitatea serviciilor furnizate de Operator prin intermediul Craftology, inclusiv intermedierea relației dintre cumpărători și vânzători, administrarea conturilor, afișarea produselor, facilitarea comenzilor și alte funcționalități disponibile utilizatorilor."
    },
    {
      "t": "h",
      "s": "Ce este Craft'zaar. Rolul de intermediar"
    },
    {
      "t": "p",
      "s": "Platforma Craft'zaar este un marketplace destinat promovării și comercializării produselor handmade realizate de artizani și mici producători din România, prin intermediul căruia sunt intermediere vânzările dintre vânzători verificați, persoane juridice independente sau profesioniști autorizați, și cumpărători. Comercializarea produselor de serie, fabricate industrial sau achiziționate în scopul revânzării este contrară conceptului Platformei și poate conduce la eliminarea produselor respective și/sau la suspendarea ori închiderea contului de vânzător."
    },
    {
      "t": "p",
      "s": "Operatorul nu este vânzătorul produselor listate de terți. Pentru produsele listate de vânzători terți, contractul de vânzare-cumpărare se încheie direct între cumpărător și vânzătorul respectiv; Operatorul oferă doar platforma tehnică și serviciile de intermediere."
    },
    {
      "t": "p",
      "s": "Produsele marcate ca aparținând brandului propriu al Operatorului sunt vândute direct de Operator. Aceste produse vor fi identificate distinct pe Platformă."
    },
    {
      "t": "p",
      "s": "Operatorul nu dobândește dreptul de proprietate asupra produselor comercializate de vânzători și nu acționează în calitate de mandatar, reprezentant, distribuitor, agent comercial sau partener contractual al vânzătorilor în relația cu cumpărătorii."
    },
    {
      "t": "p",
      "s": "Operatorul nu garantează existența, disponibilitatea, legalitatea, conformitatea, calitatea, siguranța, autenticitatea ori adecvarea produselor comercializate de vânzători și nu răspunde pentru informațiile furnizate de aceștia, cu excepția situațiilor prevăzute expres de lege."
    },
    {
      "t": "p",
      "s": "Vânzătorii sunt singurii responsabili pentru produsele listate, descrierile și fotografiile produselor, stabilirea prețurilor, emiterea documentelor fiscale, livrarea produselor, respectarea obligațiilor privind garanțiile, retururile, protecția consumatorilor și obligațiile fiscale aplicabile."
    },
    {
      "t": "p",
      "s": "Operatorul poate verifica informațiile furnizate de vânzători și poate solicita documente suplimentare pentru validarea acestora, fără ca această verificare să constituie o garanție privind activitatea, solvabilitatea, legalitatea sau conformitatea vânzătorului."
    },
    {
      "t": "h",
      "s": "Conturi"
    },
    {
      "t": "p",
      "s": "Crearea și utilizarea unui cont pe Platformă sunt permise exclusiv persoanelor care au împlinit vârsta de 18 ani și au capacitate deplină de exercițiu, precum și persoanelor juridice prin reprezentanții lor legali sau persoanele împuternicite."
    },
    {
      "t": "p",
      "s": "Prin crearea contului, declari că datele furnizate sunt reale, corecte, complete și actuale. Utilizatorul are obligația de a actualiza datele ori de câte ori intervin modificări."
    },
    {
      "t": "p",
      "s": "Utilizatorul este responsabil pentru păstrarea în siguranță și confidențialitatea datelor de autentificare asociate contului său, precum și pentru toate activitățile și operațiunile efectuate prin intermediul acestuia."
    },
    {
      "t": "p",
      "s": "Este interzisă crearea unui cont folosind date false, incomplete, aparținând altei persoane sau care pot induce în eroare Operatorul, vânzătorii ori ceilalți utilizatori."
    },
    {
      "t": "p",
      "s": "Contul este personal și nu poate fi cesionat, transferat, vândut sau pus la dispoziția unei alte persoane fără acordul prealabil al Operatorului."
    },
    {
      "t": "p",
      "s": "Utilizatorul are obligația de a notifica Operatorul fără întârziere în cazul în care suspectează accesarea neautorizată a contului sau compromiterea datelor de autentificare."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a suspenda, restricționa sau închide conturile utilizatorilor care încalcă prezentele Termene și Condiții, legislația aplicabilă, drepturile altor utilizatori ori drepturile unor terți."
    },
    {
      "t": "h",
      "s": "Cumpărători"
    },
    {
      "t": "p",
      "s": "Platforma permite cumpărătorilor să identifice/compare și să achiziționeze produsele listate de vânzători prin intermediul acesteia, în condițiile prevăzute de prezentele Termene și Condiții și de legislația aplicabilă."
    },
    {
      "t": "p",
      "s": "Prețurile produselor sunt afișate în (RON) și includ, după caz, TVA-ul aplicabil, conform informațiilor furnizate de vânzător. Costurile de livrare, vor fi indicate separat înainte de finalizarea comenzii.."
    },
    {
      "t": "p",
      "s": "Plata produselor se procesează prin intermediul furnizorilor de servicii de plată integrați în Platformă, respectiv prin Stripe Connect. Sumele achitate de cumpărători sunt procesate de furnizorul de servicii de plată, care distribuie automat sumele datorate vânzătorului și Operatorului conform mecanismului tehnic implementat. Operatorul nu stochează și nu prelucrează datele cardurilor bancare utilizate pentru efectuarea plăților."
    },
    {
      "t": "p",
      "s": "Prin plasarea unei comenzi, cumpărătorul confirmă că informațiile furnizate sunt reale, complete și actualizate și își asumă responsabilitatea pentru exactitatea datelor necesare procesării comenzii, facturării și livrării produselor."
    },
    {
      "t": "p",
      "s": "Cumpărătorul are obligația de a utiliza Platforma cu bună-credință și de a nu efectua comenzi fictive, speculative, abuzive, frauduloase sau care urmăresc perturbarea activității vânzătorilor ori a funcționării Platformei."
    },
    {
      "t": "p",
      "s": "Prin transmiterea unei comenzi, cumpărătorul confirmă intenția de a achiziționa produsul selectat și acceptă caracteristicile, prețul, termenul estimat de livrare, condițiile speciale de comercializare și orice alte informații prezentate în pagina produsului la momentul plasării comenzii."
    },
    {
      "t": "p",
      "s": "Datele de contact ale vânzătorului pot fi comunicate cumpărătorului în măsura necesară executării contractului de vânzare, inclusiv pentru comunicări privind confirmarea comenzii, livrarea produselor, retururile, garanțiile și soluționarea eventualelor reclamații."
    },
    {
      "t": "p",
      "s": "Drepturile consumatorilor privind retragerea din contract, garanția legală de conformitate, retururile și rambursările sunt reglementate de legislația aplicabilă și sunt detaliate în Politica de Retururi și Rambursări disponibilă pe Platformă."
    },
    {
      "t": "h",
      "s": "Vânzători"
    },
    {
      "t": "p",
      "s": "Vânzarea pe Platformă este permisă doar persoanelor juridice, PFA, întreprinderilor individuale sau altor profesioniști autorizați, care au fost verificați și aprobați de Operator și care au acceptat Acordul Vânzătorului."
    },
    {
      "t": "p",
      "s": "Vânzătorul are obligația de a comercializa exclusiv produse care corespund specificului artizanal al Platformei, sunt legale, conforme, autentice, disponibile și descrise în mod corect. Este interzisă listarea produselor industriale, de serie, a produselor de import prezentate în mod fals ca fiind realizate manual, precum și a produselor achiziționate în vederea revânzării."
    },
    {
      "t": "p",
      "s": "Vânzătorul garantează că produsele comercializate, precum și fotografiile, descrierile, textele, mărcile, imaginile și celelalte materiale încărcate pe Platformă nu încalcă drepturile niciunui terț."
    },
    {
      "t": "p",
      "s": "Vânzătorul răspunde de produsele sale, de facturare, livrare, garanție, retururi, rambursări și de respectarea tuturor obligațiilor legale aplicabile activității sale."
    },
    {
      "t": "p",
      "s": "Vânzătorul este singurul responsabil pentru respectarea legislației privind protecția consumatorilor, garanțiile legale, siguranța produselor, etichetarea, fiscalitatea, drepturile de proprietate intelectuală și orice alte obligații legale aplicabile produselor comercializate."
    },
    {
      "t": "p",
      "s": "Vânzătorul are obligația de a menține actualizate informațiile privind produsele comercializate, inclusiv disponibilitatea acestora, prețurile, caracteristicile și termenul estimat de livrare."
    },
    {
      "t": "p",
      "s": "În cazul în care un produs nu mai este disponibil ori nu mai poate fi livrat în condițiile prezentate pe Platformă, Vânzătorul are obligația de a actualiza imediat informațiile respective sau de a retrage produsul de la comercializare."
    },
    {
      "t": "p",
      "s": "Vânzătorul are obligația de a coopera cu Operatorul în soluționarea reclamațiilor formulate de cumpărători, a solicitărilor autorităților competente și a sesizărilor privind încălcarea drepturilor terților."
    },
    {
      "t": "p",
      "s": "Vânzătorul nu are dreptul să utilizeze Platforma pentru a direcționa cumpărătorii către canale externe de vânzare, în scopul evitării comisionului datorat Operatorului sau a regulilor Platformei."
    },
    {
      "t": "p",
      "s": "Operatorul poate refuza aprobarea unui vânzător, poate solicita documente suplimentare, poate suspenda sau elimina un vânzător de pe Platformă în cazul încălcării prezentelor Termene și Condiții, a Acordului Vânzătorului sau a legislației aplicabile."
    },
    {
      "t": "h",
      "s": "Listarea produselor"
    },
    {
      "t": "p",
      "s": "Produsele listate trebuie să fie descrise în mod exact, complet și corect, astfel încât cumpărătorul să poată lua o decizie informată."
    },
    {
      "t": "p",
      "s": "Descrierea produsului trebuie să includă informațiile relevante privind natura produsului, materialele utilizate, dimensiunile, culoarea, modul de utilizare, întreținerea, eventualele limitări, termenul estimat de realizare sau livrare și orice alte caracteristici importante."
    },
    {
      "t": "p",
      "s": "Fotografiile produselor trebuie să fie reale, clare și să reflecte cât mai fidel produsul oferit spre vânzare. Este interzisă listarea unui produs ca fiind disponibil dacă acesta nu poate fi livrat sau realizat conform descrierii și termenului indicat."
    },
    {
      "t": "p",
      "s": "În cazul produselor personalizate, realizate la comandă sau conform specificațiilor cumpărătorului, vânzătorul are obligația de a indica acest aspect în mod clar înainte de plasarea comenzii."
    },
    {
      "t": "p",
      "s": "Vânzătorul nu poate modifica în mod unilateral prețul sau condițiile esențiale ale comenzii după plasarea acesteia, cu excepția cazurilor acceptate expres de cumpărător sau prevăzute de lege."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a elimina, suspenda sau solicita modificarea oricărei listări care este incompletă, inexactă, înșelătoare, neconformă cu regulile Platformei sau care poate încălca legea ori drepturile unor terți."
    },
    {
      "t": "h",
      "s": "Produse și activități interzise"
    },
    {
      "t": "p",
      "s": "Este interzisă listarea, promovarea, comercializarea sau facilitarea vânzării prin intermediul Platformei a produselor care încalcă legea, prezentele Termene și Condiții sau drepturile unor terți."
    },
    {
      "t": "p",
      "s": "Sunt interzise, cu titlu exemplificativ și fără a se limita la acestea:"
    },
    {
      "t": "li",
      "s": "produse contrafăcute, piratate sau care încalcă drepturi de autor, mărci, desene, modele ori alte drepturi de proprietate intelectuală;"
    },
    {
      "t": "li",
      "s": "produse furate, obținute ilegal sau asupra cărora vânzătorul nu are drept de dispoziție;"
    },
    {
      "t": "li",
      "s": "produse periculoase, nesigure sau retrase de autorități ori semnalate ca prezentând riscuri pentru consumatori;"
    },
    {
      "t": "li",
      "s": "arme, muniții, articole explozive, materiale inflamabile sau alte produse periculoase ori supuse unor regimuri speciale de autorizare;"
    },
    {
      "t": "li",
      "s": "droguri, substanțe psihotrope, substanțe halucinogene sau alte produse interzise de lege;"
    },
    {
      "t": "li",
      "s": "medicamente, suplimente alimentare, produse medicale, produse cosmetice, produse alimentare, băuturi alcoolice, produse din tutun sau alte produse excluse de la comercializare prin politica Platformei;"
    },
    {
      "t": "li",
      "s": "produse cu conținut obscen, pornografic, discriminatoriu, instigator la ură, violență sau care afectează demnitatea umană;"
    },
    {
      "t": "li",
      "s": "produse care conțin date personale, liste de contacte, parole, conturi de acces sau alte informații confidențiale;"
    },
    {
      "t": "li",
      "s": "produse care pot încălca bunele moravuri, ordinea publică sau drepturile și interesele legitime ale altor persoane;"
    },
    {
      "t": "li",
      "s": "orice alte produse a căror vânzare online este interzisă sau restricționată potrivit legislației aplicabile;"
    },
    {
      "t": "li",
      "s": "produse de import prezentate în mod fals ca produse handmade;"
    },
    {
      "t": "p",
      "s": "produse industriale sau de serie care nu corespund specificului Platformei."
    },
    {
      "t": "p",
      "s": "Operatorul poate stabili oricând reguli suplimentare privind categoriile de produse permise sau interzise pe Platformă."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a solicita documente, certificate, autorizații sau alte dovezi privind legalitatea și conformitatea produselor comercializate."
    },
    {
      "t": "p",
      "s": "Refuzul furnizării documentelor solicitate poate conduce la suspendarea produsului sau a contului vânzătorului."
    },
    {
      "t": "h",
      "s": "Conduită interzisă"
    },
    {
      "t": "p",
      "s": "Este interzis:"
    },
    {
      "t": "li",
      "s": "să listezi produse ilegale, contrafăcute, periculoase sau care încalcă drepturile unor terți;"
    },
    {
      "t": "li",
      "s": "să publici conținut fals, înșelător, incomplet sau susceptibil să inducă în eroare utilizatorii;"
    },
    {
      "t": "li",
      "s": "să utilizezi Platforma în scopuri frauduloase, abuzive sau contrare legii;"
    },
    {
      "t": "li",
      "s": "să hărțuiești, ameninți, defăimezi sau discriminezi alți utilizatori;"
    },
    {
      "t": "li",
      "s": "să încerci eludarea comisionului datorat Operatorului ori realizarea tranzacțiilor în afara Platformei, atunci când acestea au fost inițiate prin intermediul Platformei;"
    },
    {
      "t": "li",
      "s": "să folosești date false sau identitatea altei persoane;"
    },
    {
      "t": "li",
      "s": "să încerci accesarea neautorizată a conturilor, sistemelor, serverelor sau bazelor de date ale Platformei;"
    },
    {
      "t": "li",
      "s": "să introduci viruși, coduri malițioase sau alte elemente care pot afecta funcționarea Platformei;"
    },
    {
      "t": "li",
      "s": "să copiezi, extragi, colectezi sau reutilizezi conținutul Platformei fără acordul Operatorului, cu excepția cazurilor permise de lege;"
    },
    {
      "t": "p",
      "s": "să utilizezi Platforma într-un mod care poate prejudicia imaginea, funcționarea, securitatea sau interesele legitime ale Operatorului, vânzătorilor, cumpărătorilor ori terților."
    },
    {
      "t": "h",
      "s": "10. Conținut generat de utilizatori"
    },
    {
      "t": "p",
      "s": "În măsura în care Platforma permite publicarea de recenzii, evaluări, comentarii, întrebări, răspunsuri, mesaje sau alte forme de conținut generat de utilizatori, aceștia sunt singurii responsabili pentru conținutul publicat."
    },
    {
      "t": "p",
      "s": "Utilizatorii au obligația de a publica exclusiv informații reale, licite, relevante și care nu încalcă drepturile, interesele legitime sau imaginea altor persoane."
    },
    {
      "t": "p",
      "s": "Este interzisă publicarea de conținut fals, înșelător, denigrator, defăimător, ofensator, discriminatoriu, abuziv, obscen ori contrar legii sau bunelor moravuri."
    },
    {
      "t": "p",
      "s": "Operatorul nu are obligația de a verifica în prealabil conținutul publicat de utilizatori, însă își rezervă dreptul de a elimina, restricționa sau ascunde orice conținut care încalcă legea, drepturile terților, prezentele Termene și Condiții ori care poate afecta funcționarea, imaginea sau reputația Platformei."
    },
    {
      "t": "h",
      "s": "Mesagerie și comunicări prin Platformă"
    },
    {
      "t": "p",
      "s": "În măsura în care Platforma pune la dispoziția utilizatorilor funcționalități de mesagerie, comunicare directă, notificări, întrebări sau răspunsuri, acestea trebuie utilizate exclusiv în scopuri legate de comenzile și activitatea desfășurată prin Platformă."
    },
    {
      "t": "p",
      "s": "Este interzisă folosirea acestor instrumente pentru hărțuire, transmiterea de conținut ilegal, spam, comunicări comerciale nesolicitate, redirecționarea tranzacțiilor în afara Platformei sau pentru orice alte activități contrare legii ori prezentelor Termene și Condiții."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a analiza, în limitele legii și ale politicilor sale interne, sesizările privind utilizarea abuzivă a instrumentelor de comunicare și de a lua măsurile pe care le consideră necesare pentru protejarea Platformei și a utilizatorilor."
    },
    {
      "t": "p",
      "s": "Comunicările purtate prin intermediul funcționalităților de mesagerie au loc direct între utilizatori. Operatorul nu este parte a acestor discuții, nu negociază și nu încheie tranzacții în numele utilizatorilor și nu răspunde pentru conținutul sau consecințele comunicărilor dintre aceștia."
    },
    {
      "t": "h",
      "s": "Raportarea conținutului ilegal sau neconform"
    },
    {
      "t": "p",
      "s": "Orice utilizator sau terț poate sesiza Operatorul cu privire la existența unor produse, informații, materiale sau activități care încalcă legea, drepturile terților sau prezentele Termene și Condiții."
    },
    {
      "t": "p",
      "s": "Pot face obiectul raportării inclusiv produsele care nu respectă specificul handmade al Platformei, produsele de import prezentate ca produse handmade, precum și situațiile în care există suspiciuni că un vânzător nu îndeplinește condițiile de eligibilitate stabilite de Platformă."
    },
    {
      "t": "p",
      "s": "Sesizările pot fi transmise la adresa de email info.craftology.shop@gmail.com sau accesand formularul de raportare prezent la pagina produsului/ vanzatorului cu indicarea, pe cât posibil, a următoarelor informații:"
    },
    {
      "t": "li",
      "s": "identificarea produsului, conținutului sau activității reclamate;"
    },
    {
      "t": "li",
      "s": "link-ul sau elementele necesare pentru localizarea conținutului;"
    },
    {
      "t": "li",
      "s": "motivele pentru care se consideră că produsul sau conținutul este ilegal ori neconform;"
    },
    {
      "t": "li",
      "s": "datele de contact ale persoanei care formulează sesizarea;"
    },
    {
      "t": "p",
      "s": "o declarație că informațiile furnizate sunt reale și complete, potrivit cunoștințelor persoanei care sesizează."
    },
    {
      "t": "p",
      "s": "Operatorul va analiza sesizările primite și, după caz, poate dispune eliminarea conținutului, suspendarea listării, restricționarea accesului, solicitarea de clarificări, notificarea vânzătorului sau orice alte măsuri necesare."
    },
    {
      "t": "p",
      "s": "Operatorul poate refuza luarea unor măsuri în cazul sesizărilor vădit nefondate, incomplete, abuzive sau formulate cu rea-credință."
    },
    {
      "t": "p",
      "s": "Utilizatorii au obligația de a utiliza cu bună-credință mecanismele de raportare puse la dispoziție de Operator.Transmiterea repetată de sesizări vădit nefondate, abuzive sau formulate cu rea-credință poate conduce la restricționarea accesului la aceste funcționalități sau la aplicarea altor măsuri prevăzute de prezentele Termene și Condiții."
    },
    {
      "t": "h",
      "s": "Măsuri privind conținutul, produsele și conturile"
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a lua măsuri atunci când constată sau are suspiciuni rezonabile că un produs, conținut, cont ori activitate încalcă legea, drepturile terților sau prezentele Termene și Condiții."
    },
    {
      "t": "p",
      "s": "Măsurile pot include, fără a se limita la:"
    },
    {
      "t": "li",
      "s": "solicitarea de clarificări sau documente suplimentare;"
    },
    {
      "t": "li",
      "s": "avertizarea utilizatorului;"
    },
    {
      "t": "li",
      "s": "modificarea sau solicitarea modificării conținutului;"
    },
    {
      "t": "li",
      "s": "suspendarea temporară a produsului sau a contului;"
    },
    {
      "t": "li",
      "s": "eliminarea produsului sau a conținutului;"
    },
    {
      "t": "li",
      "s": "restricționarea accesului la anumite funcționalități;"
    },
    {
      "t": "li",
      "s": "închiderea contului;"
    },
    {
      "t": "p",
      "s": "notificarea autorităților competente, dacă situația impune acest lucru."
    },
    {
      "t": "p",
      "s": "În funcție de circumstanțe, Operatorul poate aplica măsuri gradual, inclusiv avertisment, suspendare temporară, suspendare pe termen determinat sau eliminarea definitivă a contului ori a produsului."
    },
    {
      "t": "p",
      "s": "În situațiile în care există suspiciuni rezonabile privind caracterul ilegal, fraudulos sau periculos al unui produs ori al unei activități, Operatorul poate dispune suspendarea imediată a produsului sau contului până la clarificarea situației."
    },
    {
      "t": "p",
      "s": "Măsurile vor fi proporționale cu natura încălcării, gravitatea acesteia, riscurile generate și istoricul utilizatorului, cu excepția situațiilor urgente în care Operatorul poate lua măsuri imediate pentru protejarea Platformei, a utilizatorilor ori a terților."
    },
    {
      "t": "h",
      "s": "Proprietate intelectuală"
    },
    {
      "t": "p",
      "s": "Marca, designul, elementele grafice, structura, interfața, conținutul creat de Operator și toate elementele Platformei aparțin Operatorului sau sunt utilizate de acesta în baza unor drepturi legale."
    },
    {
      "t": "p",
      "s": "Este interzisă copierea, reproducerea, distribuirea, modificarea, publicarea, transmiterea, vânzarea, licențierea sau exploatarea în orice mod a elementelor Platformei fără acordul prealabil scris al Operatorului, cu excepția cazurilor permise de lege."
    },
    {
      "t": "p",
      "s": "Conținutul încărcat de vânzători, inclusiv fotografiile, descrierile, textele, denumirile, logo-urile și materialele aferente produselor, rămân al acestora sau al titularilor de drepturi."
    },
    {
      "t": "p",
      "s": "Prin încărcarea conținutului pe Platformă, vânzătorul acordă Operatorului o licență neexclusivă, gratuită, valabilă pe durata publicării conținutului pe Platformă, pentru afișarea, reproducerea, promovarea și utilizarea acestuia în scopul funcționării, administrării și promovării Platformei și a produselor listate."
    },
    {
      "t": "p",
      "s": "Vânzătorul declară și garantează că deține toate drepturile necesare asupra conținutului încărcat și că utilizarea acestuia de către Operator nu încalcă drepturile niciunui terț."
    },
    {
      "t": "p",
      "s": "În cazul în care Operatorul primește o sesizare privind încălcarea unor drepturi de proprietate intelectuală, acesta poate elimina sau suspenda conținutul reclamat până la clarificarea situației."
    },
    {
      "t": "p",
      "s": "Persoana care pretinde încălcarea unui drept de proprietate intelectuală va transmite Operatorului informații suficiente pentru identificarea conținutului reclamat, a dreptului pretins încălcat și a titularului acestuia.  Operatorul poate solicita documente justificative suplimentare și poate suspenda ori elimina conținutul reclamat până la clarificarea situației."
    },
    {
      "t": "h",
      "s": "15. Date cu caracter personal"
    },
    {
      "t": "p",
      "s": "Prelucrarea datelor cu caracter personal prin intermediul Platformei Craft'zaar se realizează în conformitate cu Politica de Confidențialitate, care completează prezentele Termene și Condiții și este disponibilă pe Platformă."
    },
    {
      "t": "p",
      "s": "Prin crearea unui cont pe Platformă, utilizatorul confirmă că a luat cunoștință de prevederile Politicii de Confidențialitate și, după caz, ale Politicii de Cookie-uri."
    },
    {
      "t": "p",
      "s": "În ceea ce privește produsele comercializate prin intermediul Platformei, fiecare Vânzător prelucrează, în calitate de operator de date independent, datele cu caracter personal necesare executării comenzilor, livrării produselor, emiterii documentelor fiscale, soluționării retururilor, garanțiilor, reclamațiilor și îndeplinirii obligațiilor legale care îi revin."
    },
    {
      "t": "p",
      "s": "Vânzătorul are obligația de a răspunde cu promptitudine solicitărilor și reclamațiilor formulate de cumpărători și de a depune toate diligențele necesare pentru soluționarea acestora într-un termen rezonabil."
    },
    {
      "t": "p",
      "s": "Utilizatorii au obligația de a utiliza datele cu caracter personal obținute prin intermediul Platformei exclusiv în scopul executării comenzilor, comunicării dintre cumpărători și Vânzători și îndeplinirii obligațiilor care decurg din utilizarea Platformei, cu respectarea dispozițiilor legale aplicabile și a prezentelor Termene și Condiții."
    },
    {
      "t": "p",
      "s": "Este interzisă utilizarea datelor cu caracter personal ale altor utilizatori pentru transmiterea de comunicări comerciale nesolicitate, activități de promovare, revânzare, transfer către terți, crearea unor baze de date proprii sau pentru orice alte scopuri neautorizate ori contrare legii."
    },
    {
      "t": "p",
      "s": "Fiecare Vânzător răspunde în mod direct pentru respectarea obligațiilor care îi revin în calitate de operator de date independent, în conformitate cu legislația aplicabilă privind protecția datelor cu caracter personal."
    },
    {
      "t": "h",
      "s": "16. Plăți, comisioane și procesatori de plăți"
    },
    {
      "t": "p",
      "s": "Plățile efectuate prin intermediul Platformei sunt procesate în condiții de securitate prin furnizori autorizați de servicii de plată, inclusiv prin Stripe Connect."
    },
    {
      "t": "p",
      "s": "Operatorul nu colectează, nu accesează și nu stochează datele aferente instrumentelor de plată utilizate de cumpărători. Aceste date sunt prelucrate exclusiv de furnizorul serviciilor de plată, în conformitate cu propriile politici de confidențialitate și măsuri de securitate."
    },
    {
      "t": "p",
      "s": "În cazul produselor comercializate prin intermediul Platformei, Stripe Connect facilitează procesarea plăților și distribuirea sumelor cuvenite Vânzătorului și Operatorului, potrivit condițiilor comerciale aplicabile."
    },
    {
      "t": "p",
      "s": "Comisioanele, taxele și celelalte condiții comerciale aplicabile Vânzătorilor sunt prevăzute în Acordul Vânzătorului și în documentele contractuale aplicabile."
    },
    {
      "t": "p",
      "s": "Fiecare Vânzător este singurul responsabil pentru îndeplinirea obligațiilor fiscale care îi revin în legătură cu veniturile obținute prin intermediul Platformei, inclusiv emiterea documentelor fiscale, declararea veniturilor și îndeplinirea oricăror alte obligații prevăzute de legislația aplicabilă."
    },
    {
      "t": "h",
      "s": "17. Retururi, rambursări și garanții"
    },
    {
      "t": "p",
      "s": "Produsele comercializate prin intermediul Platformei, retururile, rambursările, garanțiile și orice reclamații privind executarea contractului de vânzare sunt gestionate de Vânzător, în calitate de comerciant și parte în contractul de vânzare încheiat cu cumpărătorul."
    },
    {
      "t": "p",
      "s": "Operatorul Platformei poate facilita comunicarea dintre cumpărător și Vânzător în vederea soluționării eventualelor solicitări sau reclamații, fără a deveni parte în raportul contractual dintre aceștia și fără a-și asuma răspunderea pentru executarea obligațiilor care revin Vânzătorului."
    },
    {
      "t": "p",
      "s": "Dreptul de retragere, excepțiile de la exercitarea acestuia, garanția legală de conformitate, precum și procedura aplicabilă retururilor și rambursărilor sunt reglementate în Politica de Retururi și Rambursări, disponibilă pe Platformă."
    },
    {
      "t": "p",
      "s": "În cazul produselor personalizate, realizate la comandă sau confecționate potrivit specificațiilor cumpărătorului, dreptul de retragere poate fi limitat sau exclus, în condițiile prevăzute de legislația aplicabilă, dacă această informație a fost comunicată în mod clar cumpărătorului înainte de plasarea comenzii."
    },
    {
      "t": "h",
      "s": "18. Reclamații și soluționarea disputelor dintre utilizatori"
    },
    {
      "t": "p",
      "s": "Cumpărătorii sunt încurajați să contacteze în primul rând vânzătorul pentru orice aspect referitor la produsele comercializate, executarea comenzii, livrare, garanții, retururi sau rambursări."
    },
    {
      "t": "p",
      "s": "Reclamațiile privind produsele, livrarea, garanțiile, retururile sau rambursările vor fi adresate, cu prioritate, vânzătorului, în calitate de parte în contractul de vânzare încheiat cu cumpărătorul. În situația în care părțile nu ajung la o soluție amiabilă, Operatorul poate facilita comunicarea dintre acestea, fără a deveni parte în raportul contractual și fără a-și asuma răspunderea pentru soluționarea litigiului ori pentru executarea obligațiilor care revin Vânzătorului."
    },
    {
      "t": "p",
      "s": "Operatorul poate analiza sesizările primite privind utilizarea Platformei și poate adopta măsurile prevăzute de prezentele Termene și Condiții față de utilizatorii care încalcă legea, prezentele Termene și Condiții sau politicile Platformei, inclusiv suspendarea ori încetarea dreptului de utilizare a Platformei, atunci când sunt îndeplinite condițiile prevăzute în acestea."
    },
    {
      "t": "h",
      "s": "19. Protecția consumatorilor"
    },
    {
      "t": "p",
      "s": "Cumpărătorii beneficiază de drepturile prevăzute de legislația aplicabilă în materia protecției consumatorilor."
    },
    {
      "t": "p",
      "s": "Pentru reclamații privind drepturile consumatorilor, cumpărătorul se poate adresa vânzătorului, în calitate de comerciant și parte în contractul de vânzare, precum și Autorității Naționale pentru Protecția Consumatorilor (ANPC), în condițiile legii."
    },
    {
      "t": "p",
      "s": "În ceea ce privește produsele comercializate prin intermediul Platformei, răspunderea legală față de consumator revine vânzătorului, în calitate de comerciant și operator economic responsabil pentru executarea contractului de vânzare."
    },
    {
      "t": "p",
      "s": "Operatorul Platformei încurajează soluționarea directă și amiabilă a eventualelor neînțelegeri dintre cumpărători și vânzători și poate facilita comunicarea dintre aceștia, fără a deveni parte în raportul contractual și fără a-și asuma răspunderea pentru soluționarea litigiilor dintre aceștia."
    },
    {
      "t": "h",
      "s": "20. Limitarea răspunderii Operatorului"
    },
    {
      "t": "p",
      "s": "În limitele permise de lege, Operatorul nu răspunde pentru calitatea, conformitatea, siguranța, autenticitatea, legalitatea, disponibilitatea, descrierea sau livrarea produselor comercializate de vânzători, acestea fiind responsabilitatea exclusivă a vânzătorului."
    },
    {
      "t": "p",
      "s": "Operatorul pune la dispoziția utilizatorilor o platformă de tip marketplace și nu este parte în contractele de vânzare încheiate între cumpărători și cânzători."
    },
    {
      "t": "p",
      "s": "Operatorul nu verifică în mod individual și sistematic fiecare produs, descriere, fotografie, informație sau alt material publicat de vânzători ori de utilizatori și nu garantează că informațiile publicate de aceștia sunt întotdeauna exacte, complete, actuale sau lipsite de erori."
    },
    {
      "t": "p",
      "s": "Operatorul nu răspunde pentru prejudiciile rezultate din raporturile contractuale dintre cumpărători și vânzători, inclusiv pentru neexecutarea, executarea necorespunzătoare sau executarea cu întârziere a obligațiilor asumate de aceștia."
    },
    {
      "t": "p",
      "s": "Operatorul depune eforturi rezonabile pentru asigurarea funcționării Platformei, însă nu garantează disponibilitatea neîntreruptă a acesteia, lipsa oricăror erori, compatibilitatea cu toate dispozitivele sau accesul permanent la toate funcționalitățile oferite."
    },
    {
      "t": "p",
      "s": "Operatorul nu răspunde pentru întreruperi, erori, disfuncționalități, pierderi de date ori alte incidente cauzate de lucrări de mentenanță, de furnizori terți, de defecțiuni ale rețelelor de comunicații, atacuri informatice, cazuri de forță majoră sau alte împrejurări aflate în afara controlului său rezonabil."
    },
    {
      "t": "p",
      "s": "Operatorul nu poate fi ținut răspunzător pentru informațiile, descrierile, promisiunile, reprezentările sau declarațiile formulate exclusiv de vânzători cu privire la produsele comercializate prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Nicio prevedere din prezentele Termene și Condiții nu limitează sau înlătură drepturile consumatorilor conferite prin dispozițiile legale imperative aplicabile."
    },
    {
      "t": "h",
      "s": "Despăgubirea Operatorului"
    },
    {
      "t": "p",
      "s": "Utilizatorul și, în special, vânzătorul, se obligă să despăgubească Operatorul pentru orice prejudiciu, pierdere, cost, amendă, sancțiune, cheltuială, pretenție sau cerere formulată de terți, autorități, cumpărători ori alți utilizatori, care rezultă din:"
    },
    {
      "t": "li",
      "s": "încălcarea prezentelor Termene și Condiții;"
    },
    {
      "t": "li",
      "s": "încălcarea Acordului Vânzătorului;"
    },
    {
      "t": "li",
      "s": "încălcarea legislației aplicabile;"
    },
    {
      "t": "li",
      "s": "listarea, promovarea sau vânzarea unor produse ilegale, neconforme, contrafăcute, periculoase ori care încalcă drepturile unor terți;"
    },
    {
      "t": "li",
      "s": "încălcarea drepturilor de proprietate intelectuală;"
    },
    {
      "t": "li",
      "s": "furnizarea de informații false, incomplete sau înșelătoare;"
    },
    {
      "t": "li",
      "s": "neexecutarea obligațiilor față de cumpărători;"
    },
    {
      "t": "p",
      "s": "utilizarea abuzivă, frauduloasă sau nelegală a Platformei."
    },
    {
      "t": "p",
      "s": "Despăgubirea va include, fără a se limita la, daunele directe, cheltuielile judiciare, onorariile avocațiale, costurile administrative și orice sume pe care Operatorul este obligat să le achite ca urmare a conduitei utilizatorului sau vânzătorului."
    },
    {
      "t": "h",
      "s": "Comunicări comerciale"
    },
    {
      "t": "p",
      "s": "Operatorul poate transmite utilizatorilor comunicări privind funcționarea Platformei, comenzile, contul, securitatea, modificările documentelor contractuale sau alte informații necesare utilizării serviciilor."
    },
    {
      "t": "p",
      "s": "Comunicările comerciale, promoționale sau de marketing vor fi transmise în condițiile legii și, acolo unde este necesar, pe baza consimțământului utilizatorului."
    },
    {
      "t": "p",
      "s": "Utilizatorul se poate dezabona de la comunicările comerciale, fără ca acest lucru să afecteze comunicările necesare pentru funcționarea contului, executarea comenzilor sau respectarea obligațiilor legale."
    },
    {
      "t": "h",
      "s": "Modificarea Termenilor"
    },
    {
      "t": "p",
      "s": "Operatorul poate actualiza, modifica sau completa prezentele Termene și Condiții."
    },
    {
      "t": "p",
      "s": "Versiunea în vigoare este cea publicată pe Platformă."
    },
    {
      "t": "p",
      "s": "Modificările importante vor fi comunicate utilizatorilor prin Platformă, e-mail sau alte mijloace adecvate, într-un termen rezonabil anterior sau ulterior intrării în vigoare, după caz."
    },
    {
      "t": "p",
      "s": "Continuarea utilizării Platformei după publicarea modificărilor reprezintă acceptarea acestora, cu excepția cazurilor în care legea impune o acceptare expresă."
    },
    {
      "t": "p",
      "s": "Dacă utilizatorul nu este de acord cu modificările, acesta poate înceta utilizarea Platformei și poate solicita închiderea contului, cu respectarea obligațiilor deja asumate."
    },
    {
      "t": "h",
      "s": "24. Suspendarea, restricționarea și încetarea accesului"
    },
    {
      "t": "p",
      "s": "Operatorul poate suspenda, restricționa sau înceta, temporar ori definitiv, dreptul unui utilizator de a accesa sau utiliza Platforma în cazul în care acesta:"
    },
    {
      "t": "li",
      "s": "a) încalcă prevederile prezentelor Termene și Condiții, politicile Platformei sau dispozițiile legale aplicabile;"
    },
    {
      "t": "li",
      "s": "b) încalcă drepturile sau interesele legitime ale altor utilizatori ori ale unor terți;"
    },
    {
      "t": "li",
      "s": "c) utilizează Platforma în mod fraudulos, abuziv, necorespunzător sau contrar scopului pentru care aceasta a fost creată;"
    },
    {
      "t": "li",
      "s": "d) furnizează informații false, incomplete, inexacte sau înșelătoare;"
    },
    {
      "t": "li",
      "s": "e)publică sau comercializează produse interzise, neconforme, contrafăcute, periculoase ori care încalcă drepturile unor terți;"
    },
    {
      "t": "li",
      "s": "f) generează reclamații întemeiate ori desfășoară activități care afectează în mod semnificativ experiența celorlalți utilizatori;"
    },
    {
      "t": "li",
      "s": "g) afectează funcționarea, securitatea, reputația sau interesele legitime ale Platformei;"
    },
    {
      "t": "p",
      "s": "h) încearcă să eludeze comisioanele, regulile Platformei sau mecanismele tehnice de funcționare ale acesteia."
    },
    {
      "t": "p",
      "s": "În funcție de natura și gravitatea încălcării, Operatorul poate dispune una sau mai multe dintre următoarele măsuri: avertisment, eliminarea conținutului publicat, suspendarea temporară a contului, restricționarea accesului la anumite funcționalități sau încetarea definitivă a dreptului de utilizare a Platformei, cu sau fără notificare prealabilă, atunci când acest lucru este necesar pentru protejarea utilizatorilor, a Platformei, a terților ori pentru respectarea obligațiilor legale."
    },
    {
      "t": "p",
      "s": "Vânzătorul nu poate solicita închiderea contului cât timp există comenzi aflate în curs de executare, reclamații nesoluționate, obligații restante față de cumpărători sau alte situații care impun păstrarea contului pentru respectarea obligațiilor legale ori contractuale."
    },
    {
      "t": "h",
      "s": "25. Retragerea produselor de pe Platformă"
    },
    {
      "t": "p",
      "s": "Operatorul poate retrage temporar sau definitiv orice produs listat pe Platformă, fără notificare prealabilă atunci când acest lucru este justificat, în cazul în care există indicii că produsul încalcă dispozițiile legale aplicabile, drepturile unor terți, prezentele Termene și Condiții sau politicile Platformei ori poate genera riscuri pentru utilizatori, pentru Platformă sau pentru terți."
    },
    {
      "t": "p",
      "s": "Operatorul poate solicita vânzătorului informații sau documente suplimentare privind produsul listat, iar până la clarificarea situației poate suspenda afișarea acestuia pe Platformă."
    },
    {
      "t": "p",
      "s": "Retragerea sau suspendarea unui produs nu exonerează vânzătorul de răspunderea pentru obligațiile asumate față de cumpărători sau față de terți și nu împiedică Operatorul să adopte orice alte măsuri prevăzute de prezentele Termene și Condiții, atunci când sunt îndeplinite condițiile pentru aplicarea acestora."
    },
    {
      "t": "h",
      "s": "Forța majoră și cazul fortuit"
    },
    {
      "t": "p",
      "s": "Operatorul nu răspunde pentru neexecutarea sau executarea cu întârziere a obligațiilor sale atunci când aceasta este cauzată de evenimente de forță majoră, caz fortuit sau alte împrejurări aflate în afara controlului său rezonabil."
    },
    {
      "t": "p",
      "s": "Astfel de evenimente pot include, fără a se limita la, calamități naturale, războaie, acte de terorism, epidemii, pandemii, greve, întreruperi ale serviciilor de internet, atacuri informatice, întreruperi ale serviciilor furnizorilor terți, modificări legislative sau măsuri dispuse de autorități."
    },
    {
      "t": "h",
      "s": "Notificări"
    },
    {
      "t": "p",
      "s": "Comunicările dintre Operator și utilizatori se pot realiza prin e-mail, notificări în Platformă, mesaje în cont sau prin alte mijloace de comunicare puse la dispoziție de Operator."
    },
    {
      "t": "p",
      "s": "Notificările transmise de Operator la adresa de e-mail comunicată de utilizator se consideră primite la data transmiterii, cu excepția cazului în care Operatorul primește un mesaj automat de eroare privind imposibilitatea livrării. Utilizatorul are obligația de a menține actualizate datele de contact asociate contului."
    },
    {
      "t": "h",
      "s": "Nulitate parțială"
    },
    {
      "t": "p",
      "s": "În cazul în care oricare dintre prevederile prezentelor Termene și Condiții este considerată nulă, nelegală sau inaplicabilă, celelalte prevederi vor rămâne valabile și aplicabile."
    },
    {
      "t": "p",
      "s": "Prevederea nulă sau inaplicabilă va fi înlocuită, în măsura permisă de lege, cu o prevedere valabilă care reflectă cât mai fidel scopul economic și juridic al prevederii inițiale."
    },
    {
      "t": "h",
      "s": "Legea aplicabilă și soluționarea litigiilor"
    },
    {
      "t": "p",
      "s": "Înainte de inițierea unui litigiu, părțile sunt încurajate să încerce soluționarea amiabilă a diferendului."
    },
    {
      "t": "p",
      "s": "Prezenții Termeni și Condiții sunt supuși legislației române."
    },
    {
      "t": "p",
      "s": "Orice litigiu izvorât din sau în legătură cu utilizarea Platformei va fi soluționat de instanțele competente din România, potrivit dispozițiilor legale aplicabile."
    },
    {
      "t": "p",
      "s": "În raporturile cu consumatorii, competența instanțelor și drepturile conferite acestora de legislația privind protecția consumatorilor rămân pe deplin aplicabile."
    },
    {
      "t": "h",
      "s": "Contact"
    },
    {
      "t": "p",
      "s": "Pentru orice întrebări, solicitări, sesizări sau reclamații privind Platforma ori prezentele Termene și Condiții, ne poți contacta la: info.craftology.shop@gmail.com"
    }
  ],
};

export const SELLER_AGREEMENT: LegalDocContent = {
  title: "Acordul Vânzătorului",
  updated: "2 iulie 2026",
  blocks: [
    {
      "t": "h",
      "s": "1. Părțile"
    },
    {
      "t": "p",
      "s": "Platforma: Craft'zaar, persoană juridică română, având CUI RO24386414, înregistrată la Registrul Comerțului sub nr. J40/64417/2008, cu sediul în Bucuresti, str Odobesti 13, blV35/60, denumită în continuare „Operatorul”."
    },
    {
      "t": "p",
      "s": "Vânzătorul: orice persoană juridică, PFA, întreprindere individuală sau alt profesionist autorizat care se înscrie ca vânzător pe Platforma Craft'zaar în vederea comercializării de produse handmade, artizanale, personalizate sau realizate la comandă, în condițiile stabilite prin prezentul Acord, denumit în continuare „Vânzătorul”."
    },
    {
      "t": "p",
      "s": "Prezentul Acord se consideră acceptat de Vânzător la momentul înscrierii pe Platformă și reglementează raporturile dintre Operator și Vânzător privind utilizarea serviciilor oferite prin intermediul Platformei și comercializarea produselor prin intermediul acesteia."
    },
    {
      "t": "h",
      "s": "2. Eligibilitate"
    },
    {
      "t": "p",
      "s": "Vânzătorul trebuie să fie persoană juridică (SRL / PFA / II / etc.) cu CUI valid, capabilă să emită facturi către cumpărători și să desfășoare în mod legal activități de comercializare a produselor oferite prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Vânzătorul furnizează la înscriere: denumirea firmei, CUI, date de contact reale și actualizate, precum și o descriere a atelierului, activității desfășurate și a produselor comercializate."
    },
    {
      "t": "p",
      "s": "Platforma este destinată în principal artizanilor și micilor producători care comercializează produse handmade, inclusiv produse personalizate sau realizate la comandă."
    },
    {
      "t": "p",
      "s": "Vânzătorul declară și garantează că informațiile furnizate la înscriere sunt reale, complete și actualizate și se obligă să actualizeze fără întârziere orice modificare intervenită ulterior."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a refuza înscrierea sau de a solicita informații suplimentare în cazul în care datele furnizate sunt incomplete, inexacte sau ridică suspiciuni cu privire la eligibilitatea Vânzătorului."
    },
    {
      "t": "p",
      "s": "Vânzătorul acceptă prezentul Acord, Termenii și Condițiile generale ale Platformei și Politica de Confidențialitate, acestea formând împreună cadrul contractual aplicabil utilizării Platformei ."
    },
    {
      "t": "h",
      "s": "3. Verificare și aprobare"
    },
    {
      "t": "p",
      "s": "Cererile sunt verificate manual de Operator. Operatorul poate aproba, respinge sau cere clarificări, la discreția sa rezonabilă, pentru a menține calitatea pieței și pentru a se asigura că activitatea și produsele propuse spre comercializare corespund specificului Platformei."
    },
    {
      "t": "p",
      "s": "În cadrul procesului de verificare, Operatorul poate solicita informații suplimentare privind activitatea desfășurată, produsele comercializate, atelierul, modalitatea de producție sau orice alte informații necesare pentru evaluarea eligibilității Vânzătorului."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a refuza aprobarea unui cont de vânzător în cazul în care informațiile furnizate sunt incomplete, inexacte, neactualizate ori dacă apreciază în mod rezonabil că activitatea sau produsele propuse nu corespund conceptului și standardelor Platformei."
    },
    {
      "t": "p",
      "s": "După aprobare, Vânzătorul finalizează înscrierea în Stripe Connect (verificare de identitate/KYC efectuată de Stripe)."
    },
    {
      "t": "p",
      "s": "Vânzătorul poate publica produse doar după ce Stripe confirmă activarea contului."
    },
    {
      "t": "p",
      "s": "Operatorul nu are niciun control asupra procedurilor de verificare efectuate de Stripe și nu răspunde pentru refuzul, suspendarea sau limitarea serviciilor furnizate de acesta."
    },
    {
      "t": "p",
      "s": "Aprobarea contului de vânzător nu garantează menținerea permanentă a acestuia pe Platformă, Operatorul având dreptul de a suspenda sau retrage aprobarea în condițiile prevăzute de prezentul Acord."
    },
    {
      "t": "p",
      "s": "Operatorul poate solicita, pe durata utilizării Platformei, informații suplimentare sau clarificări privind activitatea desfășurată și produsele comercializate, în vederea verificării respectării condițiilor de eligibilitate și a specificului handmade al Platformei."
    },
    {
      "t": "h",
      "s": "4. Comision"
    },
    {
      "t": "p",
      "s": "Operatorul reține un comision de 10% din prețul fiecărui produs vândut prin intermediul Platformei, la care se adaugă TVA, dacă este aplicabil conform legislației fiscale în vigoare."
    },
    {
      "t": "p",
      "s": "Comisionul se reține automat la fiecare tranzacție prin Stripe, în conformitate cu mecanismul de plată implementat în Platformă."
    },
    {
      "t": "p",
      "s": "Comisioanele de procesare Stripe (aproximativ 1,5% + taxele aferente aplicabile) sunt suportate de Vânzător, acesta fiind comerciantul înregistrat al tranzacției și beneficiarul sumelor încasate din vânzarea produselor sale."
    },
    {
      "t": "p",
      "s": "Operatorul emite Vânzătorului factura aferentă comisionului datorat pentru serviciile de intermediere prestate prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Comisionul se datorează pentru toate tranzacțiile procesate și încasate prin intermediul Platformei și se reține automat la momentul efectuării plății de către cumpărător."
    },
    {
      "t": "p",
      "s": "Eventualele anulări, refuzuri, retururi, rambursări sau litigii intervenite ulterior între Vânzător și cumpărător nu afectează dreptul Operatorului de a păstra comisionul aferent serviciului de intermediere deja prestat, cu excepția situațiilor generate de o eroare tehnică imputabilă Platformei."
    },
    {
      "t": "h",
      "s": "5. Plăți"
    },
    {
      "t": "p",
      "s": "Plățile cumpărătorilor ajung direct în contul Stripe al Vânzătorului Operatorul nu deține, nu administrează și nu controlează fondurile aparținând Vânzătorului."
    },
    {
      "t": "p",
      "s": "Stripe efectuează plățile către contul bancar al Vânzătorului conform programului configurat (în mod implicit săptămânal)."
    },
    {
      "t": "p",
      "s": "Operatorul nu răspunde pentru întârzieri, suspendări, blocări, verificări suplimentare sau alte măsuri aplicate de Stripe ori de instituțiile financiare implicate în procesarea plăților."
    },
    {
      "t": "p",
      "s": "Vânzătorul este responsabil pentru furnizarea unor date bancare corecte și actualizate, precum și pentru îndeplinirea tuturor condițiilor impuse de Stripe pentru utilizarea serviciilor sale."
    },
    {
      "t": "p",
      "s": "Vânzătorul este singurul responsabil pentru îndeplinirea obligațiilor fiscale, contabile și de raportare care îi revin potrivit legislației aplicabile, inclusiv pentru emiterea documentelor fiscale, declararea veniturilor, calculul și plata impozitelor, taxelor sau contribuțiilor datorate în legătură cu activitatea desfășurată prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Stripe pune la dispoziția Vânzătorului rapoartele și informațiile disponibile prin intermediul serviciului său, însă Operatorul nu verifică și nu garantează corectitudinea evidențelor fiscale ale Vânzătorului și nu poate fi ținut răspunzător pentru neîndeplinirea obligațiilor legale ale acestuia."
    },
    {
      "t": "p",
      "s": "Operatorul nu oferă consultanță fiscală, contabilă sau financiară și nu poate fi ținut răspunzător pentru modul în care Vânzătorul își îndeplinește obligațiile legale aferente activității desfășurate prin intermediul Platformei."
    },
    {
      "t": "h",
      "s": "6. Obligațiile Vânzătorului"
    },
    {
      "t": "li",
      "s": "listează doar produse legale, autentice, lucrate/deținute legitim, descrise corect prin poze și texte reale;"
    },
    {
      "t": "li",
      "s": "comercializează exclusiv produse care corespund specificului handmade și artizanal al Platformei, inclusiv produse personalizate sau realizate la comandă, atunci când acest aspect este indicat în mod clar în descrierea produsului;"
    },
    {
      "t": "li",
      "s": "nu listează produse industriale, produse de serie, produse de import prezentate ca fiind handmade ori produse achiziționate în vederea revânzării;"
    },
    {
      "t": "li",
      "s": "se asigură că informațiile privind produsele, prețurile, disponibilitatea, caracteristicile și termenul estimat de livrare sunt reale, complete și actualizate;"
    },
    {
      "t": "li",
      "s": "emite factură către cumpărător conform legii;"
    },
    {
      "t": "li",
      "s": "asigură livrarea produselor într-un termen rezonabil și comunicarea cu cumpărătorul pe întreaga durată a procesului de vânzare și livrare, datele de contact ale Vânzătorului fiind puse la dispoziția cumpărătorilor prin intermediul Platformei;"
    },
    {
      "t": "li",
      "s": "răspunde solicitărilor, sesizărilor și reclamațiilor formulate de cumpărători și depune diligențele necesare pentru soluționarea acestora într-un termen rezonabil;"
    },
    {
      "t": "li",
      "s": "gestionează retururile, rambursările și garanția produselor sale, conform legii și Politicii de Retururi aplicabile, întreaga răspundere pentru produse revenind Vânzătorului;"
    },
    {
      "t": "li",
      "s": "respectă legislația privind protecția consumatorilor și toate obligațiile legale aplicabile activității desfășurate prin intermediul Platformei;"
    },
    {
      "t": "li",
      "s": "respectă legislația aplicabilă privind protecția datelor cu caracter personal și utilizează datele obținute prin intermediul Platformei exclusiv în scopul executării comenzilor și îndeplinirii obligațiilor legale care îi revin;"
    },
    {
      "t": "li",
      "s": "menține actualizate datele de identificare, contact și plată asociate contului său;"
    },
    {
      "t": "li",
      "s": "cooperează cu Operatorul în cazul verificărilor, sesizărilor sau reclamațiilor privind activitatea desfășurată prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Vânzătorul este singurul responsabil pentru produsele comercializate, pentru conformitatea acestora cu legislația aplicabilă, pentru informațiile publicate, pentru executarea comenzilor, pentru gestionarea reclamațiilor, retururilor, rambursărilor și garanțiilor, precum și pentru relația contractuală încheiată cu cumpărătorii."
    },
    {
      "t": "h",
      "s": "7. Limite pentru vânzători noi"
    },
    {
      "t": "p",
      "s": "Vânzătorii nou înregistrați pot lista inițial maximum 20 de produse. După prima vânzare realizată prin intermediul Platformei, această limitare poate fi ridicată. Operatorul își rezervă dreptul de a ajusta în orice moment limitele aplicabile listării produselor."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a modifica, majora, reduce sau elimina aceste limite în funcție de istoricul contului, volumul activității desfășurate, respectarea prezentului Acord, reclamațiile primite sau alte criterii interne privind funcționarea Platformei."
    },
    {
      "t": "p",
      "s": "Aplicarea sau modificarea limitelor prevăzute în prezentul articol nu conferă Vânzătorului un drept dobândit de a lista un anumit număr de produse și nu limitează dreptul Operatorului de a adopta măsuri suplimentare de verificare, suspendare sau restricționare a activității unui cont, în condițiile prezentului Acord."
    },
    {
      "t": "h",
      "s": "8. Suspendarea, restricționarea și încetarea contului de Vânzător"
    },
    {
      "t": "p",
      "s": "Operatorul poate suspenda temporar sau definitiv accesul unui Vânzător la Platformă în cazul în care acesta încalcă prezentul Acord, Termenii și Condițiile Platformei, listează produse interzise, furnizează informații false sau înșelătoare, primește reclamații întemeiate repetate ori desfășoară activități care pot prejudicia Platforma, ceilalți utilizatori sau reputația acesteia."
    },
    {
      "t": "p",
      "s": "Operatorul poate suspenda temporar activitatea unui Vânzător în cazul existenței unor sesizări sau reclamații privind produsele comercializate ori respectarea condițiilor de eligibilitate prevăzute de prezentul Acord, până la verificarea și clarificarea situației."
    },
    {
      "t": "p",
      "s": "În cazul în care, în urma verificărilor efectuate, se constată că produsele comercializate nu respectă specificul handmade și artizanal al Platformei sau că au fost încălcate obligațiile asumate de Vânzător, Operatorul poate elimina produsele respective, restricționa activitatea contului, suspenda accesul la Platformă sau solicita remedierea situației într-un termen rezonabil."
    },
    {
      "t": "p",
      "s": "Vânzătorul poate solicita încetarea colaborării și închiderea contului, cu condiția să nu existe comenzi active, obligații neîndeplinite față de cumpărători, reclamații nesoluționate ori alte situații care impun menținerea contului până la finalizarea relațiilor comerciale existente."
    },
    {
      "t": "p",
      "s": "Comenzile aflate în derulare la data suspendării sau încetării contului trebuie onorate de Vânzător, cu excepția situațiilor în care executarea acestora este imposibilă din motive obiective sau contravine dispozițiilor legale aplicabile."
    },
    {
      "t": "p",
      "s": "Suspendarea, restricționarea sau încetarea accesului la Platformă nu afectează drepturile și obligațiile născute anterior între Vânzător, cumpărători și Operator și nu exonerează Vânzătorul de obligațiile asumate anterior datei suspendării sau încetării colaborării."
    },
    {
      "t": "h",
      "s": "9. Răspunderea Vânzătorului și limitarea răspunderii Operatorului"
    },
    {
      "t": "p",
      "s": "Vânzătorul răspunde integral față de cumpărători pentru produsele comercializate prin intermediul Platformei, inclusiv în ceea ce privește conformitatea acestora, descrierea produselor, calitatea, siguranța, livrarea, garanțiile, retururile, rambursările și respectarea obligațiilor legale aplicabile."
    },
    {
      "t": "p",
      "s": "Vânzătorul este singurul responsabil pentru informațiile publicate cu privire la produsele sale, pentru executarea comenzilor și pentru relația contractuală încheiată cu cumpărătorii."
    },
    {
      "t": "p",
      "s": "Operatorul acționează exclusiv în calitate de intermediar și furnizor al Platformei tehnice care facilitează interacțiunea dintre Vânzători și cumpărători. Operatorul nu este parte în contractele încheiate între aceștia și nu dobândește proprietatea asupra produselor comercializate prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Operatorul nu răspunde pentru existența, calitatea, autenticitatea, conformitatea, siguranța, legalitatea, disponibilitatea, livrarea sau orice alte caracteristici ale produselor comercializate de Vânzători și nu poate fi ținut răspunzător pentru neexecutarea sau executarea necorespunzătoare a obligațiilor asumate de aceștia față de cumpărători."
    },
    {
      "t": "p",
      "s": "Vânzătorul se obligă să despăgubească și să exonereze Operatorul de orice pretenții, reclamații, sancțiuni, amenzi, prejudicii, costuri sau cheltuieli generate de încălcarea de către Vânzător a prezentului Acord, a legislației aplicabile sau a drepturilor cumpărătorilor ori ale terților."
    },
    {
      "t": "p",
      "s": "Operatorul depune eforturi rezonabile pentru asigurarea funcționării Platformei, însă nu garantează funcționarea neîntreruptă, lipsa erorilor, disponibilitatea permanentă a serviciilor sau compatibilitatea acestora cu echipamentele și sistemele utilizate de Vânzător."
    },
    {
      "t": "p",
      "s": "În cazul în care Operatorul este chemat să răspundă față de terți pentru fapte, produse, informații sau obligații care aparțin Vânzătorului, acesta din urmă va despăgubi Operatorul pentru toate prejudiciile, cheltuielile și costurile rezonabile suportate ca urmare a respectivei situații, în măsura în care aceasta îi este imputabilă."
    },
    {
      "t": "h",
      "s": "10. Date și confidențialitate"
    },
    {
      "t": "p",
      "s": "Operatorul prelucrează datele Vânzătorului în conformitate cu Politica de Confidențialitate disponibilă pe Platformă și cu legislația aplicabilă privind protecția datelor cu caracter personal."
    },
    {
      "t": "p",
      "s": "Prin crearea și utilizarea contului de Vânzător, acesta este de acord cu prelucrarea datelor necesare administrării contului, utilizării Platformei, procesării tranzacțiilor, comunicărilor dintre părți și îndeplinirii obligațiilor legale ale Operatorului."
    },
    {
      "t": "p",
      "s": "Datele de identificare și de contact ale Vânzătorului pot fi afișate sau puse la dispoziția cumpărătorilor în măsura necesară desfășurării activității comerciale prin intermediul Platformei, inclusiv pentru comunicarea privind comenzile, livrarea produselor, reclamațiile, retururile, garanțiile sau exercitarea drepturilor consumatorilor."
    },
    {
      "t": "p",
      "s": "Vânzătorul este responsabil pentru păstrarea confidențialității datelor de acces la contul său și pentru toate activitățile desfășurate prin intermediul acestuia. Vânzătorul are obligația de a informa fără întârziere Operatorul în cazul în care constată utilizarea neautorizată a contului său sau orice incident care poate afecta securitatea acestuia."
    },
    {
      "t": "p",
      "s": "Vânzătorul este responsabil pentru modul în care utilizează datele cumpărătorilor la care are acces în legătură cu executarea comenzilor și se obligă să respecte legislația aplicabilă privind protecția datelor cu caracter personal."
    },
    {
      "t": "p",
      "s": "Operatorul nu răspunde pentru prelucrarea datelor efectuată de Vânzător în afara Platformei și nici pentru încălcarea de către acesta a obligațiilor prevăzute de legislația aplicabilă privind protecția datelor."
    },
    {
      "t": "p",
      "s": "Operatorul poate transmite Vânzătorului notificări, informări și comunicări referitoare la funcționarea Platformei, actualizarea serviciilor, modificarea documentației contractuale, obligațiile legale aplicabile sau alte aspecte relevante pentru desfășurarea activității prin intermediul Platformei."
    },
    {
      "t": "p",
      "s": "Informațiile referitoare la categoriile de date prelucrate, scopurile prelucrării, temeiurile legale, destinatarii datelor și drepturile persoanelor vizate sunt detaliate în Politica de Confidențialitate a Platformei."
    },
    {
      "t": "p",
      "s": "Vânzătorul se obligă să păstreze confidențialitatea informațiilor și datelor la care are acces prin intermediul Platformei și să nu le utilizeze în alte scopuri decât cele necesare executării comenzilor și desfășurării activității sale comerciale, cu respectarea legislației aplicabile."
    },
    {
      "t": "h",
      "s": "11. Diverse"
    },
    {
      "t": "p",
      "s": "Prezentul Acord este guvernat și interpretat în conformitate cu legislația română."
    },
    {
      "t": "p",
      "s": "Operatorul își rezervă dreptul de a modifica sau actualiza prezentul Acord ori de câte ori este necesar pentru adaptarea la modificări legislative, tehnice, operaționale sau comerciale privind funcționarea Platformei."
    },
    {
      "t": "p",
      "s": "Modificările vor fi comunicate Vânzătorilor prin intermediul Platformei, prin e-mail sau prin alte mijloace de comunicare utilizate de Operator. Continuarea utilizării Platformei și a activității de vânzare după comunicarea modificărilor reprezintă acceptarea acestora de către Vânzător."
    },
    {
      "t": "p",
      "s": "În cazul în care una sau mai multe prevederi ale prezentului Acord sunt considerate nule, nevalabile sau inaplicabile, celelalte prevederi vor rămâne valabile și vor produce efecte în continuare, în măsura permisă de lege."
    },
    {
      "t": "p",
      "s": "Eventualele litigii izvorâte din sau în legătură cu prezentul Acord vor fi soluționate pe cale amiabilă, iar în cazul în care acest lucru nu este posibil, de instanțele competente potrivit legislației române."
    },
    {
      "t": "p",
      "s": "Prezentul Acord se consideră acceptat de Vânzător la data finalizării procesului de înscriere și a acceptării acestuia prin intermediul Platformei."
    }
  ],
};

