// Generates src/content/legal.ts from the lawyer's extracted ODT text — VERBATIM.
// The text is machine-copied (never retyped) so nothing is truncated or altered.
// Light classification (heading / bullet / paragraph) is cosmetic only; every
// word of the source is preserved.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const today = '2 iulie 2026'; // per the lawyer's dated Terms (2.07.2026)

// exported const name, source temp file (the lawyer's latest), clean <h1> title.
const DOCS = [
  { key: 'PRIVACY', src: 'C:/Users/ribbon/AppData/Local/Temp/claude/legal-src-0.txt', title: 'Politica de Confidențialitate' },
  { key: 'TERMS', src: 'C:/Users/ribbon/AppData/Local/Temp/claude/legal-src-1.txt', title: 'Termeni și Condiții' },
  { key: 'SELLER_AGREEMENT', src: 'C:/Users/ribbon/AppData/Local/Temp/claude/legal-src-2.txt', title: 'Acordul Vânzătorului' },
  { key: 'COOKIES', src: 'C:/Users/ribbon/AppData/Local/Temp/claude/legal-src-3.txt', title: 'Politica de Cookie-uri' },
  { key: 'RETURNS', src: 'C:/Users/ribbon/AppData/Local/Temp/claude/legal-src-4.txt', title: 'Politica de Retururi și Rambursări' },
];

// Owner-authorised standardisation of the docs' identity + brand + lawyer typos:
// email → info.craftology.shop@gmail.com, brand → Craft'zaar, address → blv 35/60.
function normalize(s) {
  return s
    // Fix the capital-C email typo (Returns doc) BEFORE the brand replace, so the
    // lowercase email domain survives the case-sensitive "Craftology" swap below.
    .replaceAll('info.Craftology.shop', 'info.craftology.shop')
    .replaceAll('l.decokubik@gmail.com', 'info.craftology.shop@gmail.com')
    // Missing-T brand typo in the Returns doc ("Craf'zaar" → "Craft'zaar").
    .replaceAll("CRAF'ZAAR", "Craft'zaar")
    .replaceAll("Craf'Zaar", "Craft'zaar")
    .replaceAll("Craf'zaar", "Craft'zaar")
    // Old brand → new brand (case-sensitive; the email domain is now lowercase).
    .replaceAll('Craftology', "Craft'zaar")
    // Address consistency.
    .replaceAll('str Odobesti 13/ aprt 60', 'str Odobesti 13, blv 35/60')
    .replaceAll('blV35/60', 'blv 35/60')
    .replaceAll('blv35/60', 'blv 35/60');
}

const isDateLine = (l) => /^(Data ultimei actualizări|Ultima actualizare)/i.test(l);

function classify(line) {
  // Bullet: explicit "• " prefix (Seller Agreement) or a line ending in ";"
  if (line.startsWith('• ')) return { t: 'li', s: line.slice(2).trim() };
  if (line.startsWith('•')) return { t: 'li', s: line.slice(1).trim() };
  if (/;$/.test(line)) return { t: 'li', s: line };
  // Heading: short, no sentence-ending punctuation (covers "1. Foo", "Conturi")
  if (line.length <= 80 && !/[.;:,]$/.test(line)) return { t: 'h', s: line };
  return { t: 'p', s: line };
}

function build(src) {
  const raw = readFileSync(src, 'utf8');
  const lines = raw.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 0);
  const heading = lines.shift(); // first line = the document's own title (dropped; page shows a clean <h1>)
  const blocks = [];
  for (const rawLine of lines) {
    if (isDateLine(rawLine)) continue; // the component renders "Ultima actualizare" itself
    blocks.push(classify(normalize(rawLine)));
  }
  return { blocks, sourceTitle: heading };
}

mkdirSync('src/content', { recursive: true });

let out = `// AUTO-GENERATED by scripts/gen-legal.mjs from the lawyer's finalised ODT
// documents. Full text, verbatim — do not edit by hand; re-run the generator.
export interface LegalBlock {
  t: 'h' | 'p' | 'li';
  s: string;
}
export interface LegalDocContent {
  title: string;
  updated: string;
  blocks: LegalBlock[];
}

`;

for (const d of DOCS) {
  const { blocks } = build(d.src);
  out += `export const ${d.key}: LegalDocContent = {\n`;
  out += `  title: ${JSON.stringify(d.title)},\n`;
  out += `  updated: ${JSON.stringify(today)},\n`;
  out += `  blocks: ${JSON.stringify(blocks, null, 2).replace(/\n/g, '\n  ')},\n`;
  out += `};\n\n`;
  console.log(`${d.key}: ${blocks.length} blocks`);
}

writeFileSync('src/content/legal.ts', out, 'utf8');
console.log('wrote src/content/legal.ts');
